version: '3.4'
networks:
  host-exposed:
    driver: bridge
  inside:
    internal: true

services:
  neo-cli-privatenet-1:
    container_name: neo-cli-privatenet-1
    environment:
      NODE_NUMBER: 1
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 60s
      test:
        - CMD
        - bash
        - '-c'
        - /opt/healthcheck-node.sh
      timeout: 10s
    image: $PRIVNET_IMAGE
    networks:
      - inside
      - host-exposed
    labels:
      autoheal: 'true'
    ports:
      - '20333:20333'
      - '30333:30333'
    restart: always

  neo-cli-privatenet-2:
    container_name: neo-cli-privatenet-2
    environment:
      NODE_NUMBER: 2
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 60s
      test:
        - CMD
        - bash
        - '-c'
        - /opt/healthcheck-node.sh
      timeout: 10s
    image: $PRIVNET_IMAGE
    networks:
      - inside
      - host-exposed
    labels:
      autoheal: 'true'
    ports:
      - '20334:20334'
      - '30334:30334'
    restart: always

  neo-cli-privatenet-3:
    container_name: neo-cli-privatenet-3
    environment:
      NODE_NUMBER: 3
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 60s
      test:
        - CMD
        - bash
        - '-c'
        - /opt/healthcheck-node.sh
      timeout: 10s
    image: $PRIVNET_IMAGE
    networks:
      - inside
      - host-exposed
    labels:
      autoheal: 'true'
    ports:
      - '20335:20335'
      - '30335:30335'
    restart: always

  neo-cli-privatenet-4:
    container_name: neo-cli-privatenet-4
    environment:
      NODE_NUMBER: 4
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 60s
      test:
        - CMD
        - bash
        - '-c'
        - /opt/healthcheck-node.sh
      timeout: 10s
    image: $PRIVNET_IMAGE
    networks:
      - inside
      - host-exposed
    labels:
      autoheal: 'true'
    ports:
      - '20336:20336'
      - '30336:30336'
    restart: always

  neo-python:
    container_name: neo-python
    depends_on:
      - neo-cli-privatenet-1
      - neo-cli-privatenet-2
      - neo-cli-privatenet-3
      - neo-cli-privatenet-4
    image: 'cityofzion/neo-python:v0.8.4'
    networks:
      - inside
      - host-exposed
    tty: true
    volumes:
      - './wallets:/wallets'
      - './scripts:/neo-python/scripts'
      - >-
        ./container-override-files/neo-python/protocol.privnet.json:/neo-python/neo/data/protocol.privnet.json

